name: Django project Deploy

on:
  push:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PG_NAME:      ${{ secrets.PG_NAME }}
      PG_USER:      ${{ secrets.PG_USER }}
      PG_PASSWORD:  ${{ secrets.PG_PASSWORD }}
      PG_HOST:      ${{ secrets.HOST }}
      PG_PORT:      ${{ secrets.PORT }}
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER:     ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB:       ${{ env.PG_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checking the repository for changes
        uses: actions/checkout@v2

      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Linting programm code
        run: flake8 --ignore E501,F401 --exclude smart_home

      - name: Testing
        run: pytest measurement/tests.py
        env:
          PG_NAME:      ${{ env.PG_NAME }}
          PG_USER:      ${{ env.PG_USER }}
          PG_PASSWORD:  ${{ env.PG_PASSWORD}}
          PG_HOST:      ${{ env.HOST }}
          PG_PORT:      ${{ env.PORT }}
  deploy:
    name: Delivery of program code changes
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Launching the update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /opt/dj_prj
            git pull origin master
            source env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            script: expect /opt/dj_prj/deploy.exp
